### PR TITLE
Fix zlib 1.2.12 vcpkg failure

### PR DESCRIPTION
**Pull request by antkmsft**
Unfortunately, we can't easily pick same SHA that we picked for updating the C++ SDK (https://github.com/Azure/azure-sdk-for-cpp/pull/4036), because `paho-mqtt` has a breaking change at that commit SHA (`fatal error C1083: Cannot open include file: 'paho-mqtt/MQTTClient.h': No such file or directory`).

So, `overrides` if not the final step, is definitely the first fix.

### CODE REVIEW

**Comment by ahsonkhan** [comment]
How come CI has been passing even without this change over the last few weeks?

It makes me wonder if we actually need this change in Embedded C, or if we aren't building the expected configuration in CI to hit the issue.

**Comment by ahsonkhan** [comment]
> because `paho-mqtt` has a breaking change at that commit SHA (`fatal error C1083: Cannot open include file: 'paho-mqtt/MQTTClient.h': No such file or directory`).

FYI @danewalton, @CIPop - luckily this should only impact samples

**Review by ahsonkhan — APPROVED** [review]
Looks good (as long as it is actually needed to build the SDK, following our steps/CI to pass).

P.S. I just noticed our SDK version in the vcpkg.json file is out-dated (1.0.0), but we don't actually ship on vcpkg, but rather use it to get our dependencies, so it isn't crucial to keep in sync.

**Comment by antkmsft** [comment]
@ahsonkhan, we do also have versions in the C++ sdk, but we have two sets of files - first are the ones that are used for vcpkg export. Those should have version updated. But they keep it updated by using a placeholder, and then the script inserts the release version. Second set of `vcpkg.json` files is for "vcpkg manifest mode" - and there, version number is not important at all.

**Comment by LarryOsterman** [comment]
Do we still need this change given that it appears that the fix is available in vcpkg?

**Comment by ahsonkhan** [comment]
That's what I am wondering too. @antkmsft do we actually need this change?

**Comment by antkmsft** [comment]
Yes, we need the fix, because baseline is at `f0aa678b7471497f1adedcc99f40e1599ad22f69` vcpkg commit:
https://github.com/Azure/azure-sdk-for-c/blob/cd62e2b78a396c3d5478d3b60c046adb72687274/vcpkg.json#L4

And at that commit, `1.2.12#2` (the version uses link that does not 404 + security patch) or `1.2.13` does not exist.

**Comment by LarryOsterman** [comment]
Why not move C to a newer baseline? That baseline is back in April.

**Comment by antkmsft** [comment]
@LarryOsterman, one of the dependencies, `paho-mqtt` appears to have a breaking change at that SHA :(

**Comment by LarryOsterman** [comment]
What is the plan to move the baseline forward? We can't remain stuck on a 6 month old package baseline for all packages.

**Comment by CIPop** [comment]
> > because `paho-mqtt` has a breaking change at that commit SHA (`fatal error C1083: Cannot open include file: 'paho-mqtt/MQTTClient.h': No such file or directory`).
> 
> FYI @danewalton, @CIPop - luckily this should only impact samples

Was this already fixed? They've just changed the include paths (which was incorrect initially). 
I have all of these fixed in my investigation branch here: https://github.com/CIPop/azure-sdk-for-c/tree/hfsm using a VCPKG from sometime in June/July.

**Pull request merged**
