### PR TITLE
Feature/zephyr support

### PR DESCRIPTION
**Pull request by dp7hgh7**
Add necessary file structure and build directives in order to be used withing the Zephyr build systems.

### CODE REVIEW

**Comment by dp7hgh7** [comment]
Hi! Can someone give a hint what exactly is going wrong?

**Comment by momuno** [comment]
Hi @dp7hgh7, we have not yet reviewed this PR but will be taking a look at it. Thank you for your contributions!

**Comment by danewalton** [comment]
Hi @dp7hgh7 just to give an update here and be as transparent as possible. Additions such as these come with an expectation of support from our team which includes both the code and validating that it works (meaning continuous build pipeline validation). Ideally we would like to support as many platforms as are out there but each addition carries with it future support time and engineering hours. We are evaluating the costs of future support and current build system additions which would make this a well supported feature.

Hopefully that makes sense...didn't want to make it feel as though we were ignoring it. Thanks for the effort!

**Comment by dp7hgh7** [comment]
Hi, hanks for the heads up so far! I'm currently implementing a generic Azure integration for a customer of mine which I intend to contribute to mainline Zephyr. Therefore I will maintain this integration anyway. Only question is, where :-D.

Caspar

**Comment by sebastianspross** [comment]
Hi @dp7hgh7, I am currently trying zephyr with IoT Hub and I am wondering if you have sample code or even documentation / tutorial you can share :)

**Comment by ericwol-msft** [comment]
@sebastianspross You might want to post this question directly the in the forked repo. https://github.com/dp7hgh7/azure-sdk-for-c/tree/feature/zephyr-support

**Comment by dp7hgh7** [comment]
Hi @sebastianspross, I have some old library code which at least worked back when I was on the project. I think I can share this but might take a few days. If you have, reach out to me on Zephyrs Discord (same username) since it's a bit easier to sync.

**Pull request closed without merging**
