### PR TITLE
Update the changelog for the 1.1.0 beta 1 release and add date.

### PR DESCRIPTION
**Pull request by ahsonkhan**
I am going through all the commits from the 1.0.0 GA release to the latest commit and captured any major customer facing changes:
https://github.com/Azure/azure-sdk-for-c/compare/5e9d7b96dbd98ce7125e4beed385959a32b4c6c1...9610c0e22990a5cc3fbe126ab2ee071d7db1426c

Please review and let me know if I missed something or if you'd like to re-word an item.

### CODE REVIEW

**Comment by ahsonkhan** [comment]
@danewalton - what, **if anything,** should we mention about https://github.com/Azure/azure-sdk-for-c/pull/1398

**Comment by danewalton** [comment]
> 
> 
> @danewalton - what, **if anything,** should we mention about #1398

I don't think we need to mention anything. It's technically an internal implementation detail.

**Review by vhvb1989 — APPROVED** [review]

**Comment by ahsonkhan** [comment]
I'll do a final spot check of the commits and merge this update after 4pm today.

**Review by antkmsft — APPROVED** [review]
Do we still plan to add storage to 1.1 beta?
Other - let's search all the "1.0.0" strings in all files, to make sure we updated everything.

**Comment by ahsonkhan** [comment]
> Do we still plan to add storage to 1.1 beta?

Ask Rick. As far as I know, that will be the next release

> Other - let's search all the "1.0.0" strings in all files, to make sure we updated everything.

Please feel free to do that in a separate PR prior to the release tomorrow. This PR is only for the CL.

**Comment by antkmsft** [comment]
> > Other - let's search all the "1.0.0" strings in all files, to make sure we updated everything.
> 
> Please feel free to do that in a separate PR prior to the release tomorrow. This PR is only for the CL.

https://github.com/Azure/azure-sdk-for-c/pull/1409

**Pull request merged**
