### PR TITLE
Fix Windows to use /MT when building static libraries

### PR DESCRIPTION
**Pull request by antkmsft**
Follow up on https://github.com/Azure/azure-sdk-for-c/pull/1338

### CODE REVIEW

**Review by ahsonkhan — DISMISSED** [review]

**Comment by ahsonkhan** [comment]
Let's hold off on merging this, and get https://github.com/Azure/azure-sdk-for-c/pull/1394 merged instead since we have a new contributor :)

**Comment by BillyONeal** [comment]
> Let's hold off on merging this, and get #1394 merged instead since we have a new contributor :)

No big deal for me; on the vcpkg team I've got fingerprints in enough repos now XD

**Comment by ahsonkhan** [comment]
C'mon, contributor number 36! It's a perfect square too.
image

**Comment by antkmsft** [comment]
image

**Comment by antkmsft** [comment]
Closing in favor of #1394.

**Pull request closed without merging**
