### PR TITLE
Revert "avoid reading address from size 0 span (#1373)"

### PR DESCRIPTION
**Pull request by vhvb1989**
This reverts commit 975a632be254d365b169d6f99d8141ba65127748.

### CODE REVIEW

**Review by ahsonkhan — APPROVED** [review]

**Comment by antkmsft** [comment]
Why are we doing this? This seemed to be a good change.

**Comment by vhvb1989** [comment]
> 
> 
> Why are we doing this? This seemed to be a good change.

Reverting to make changes correctly.  I committed more changes than what I wanted.   I will add changes again correctly

**Pull request merged**
