### PR TITLE
add ci.yml file for keyvault

### PR DESCRIPTION
**Pull request by danieljurek**

### CODE REVIEW

**Comment by bsiegel** [comment]
:shipit: 

You might notice that in `archetype-sdk-client.yml` we don't actually use the provided ServiceDirectory at all - every pipeline builds the whole project. My plan was that until we'd figured out how we were actually splitting the libraries up (monorepo vs repos per library) I wasn't going to try to figure out how to split up the CMake build to let us build libraries individually.

**Comment by vhvb1989** [comment]
I created  a PR for a proposal about how to have a simple project splitting.
https://github.com/Azure/azure-sdk-for-c/pull/170

Might be useful for setting up the pipeline for KeyVault

**Comment by vhvb1989** [comment]
Do we want to close this @danieljurek  ?

**Pull request closed without merging**
