### PR TITLE
Fix Windows to use /MT when building static libraries.

### PR DESCRIPTION
**Pull request by BillyONeal**

### CODE REVIEW

**Comment by ahsonkhan** [comment]
Related to https://github.com/Azure/azure-sdk-for-c/pull/1380

**Review by ahsonkhan — APPROVED** [review]

**Comment by ahsonkhan** [comment]
The reason the windows legs are failing in CI, because they are still using `x64-windows-static-md`.

We need to remove the 3 instances of `-md` from this yml file (similar to https://github.com/antkmsft/azure-sdk-for-c/commit/6f87a2dc98b889fa001410d81b20cf160b0fa719, to revert back  to the CI script before https://github.com/Azure/azure-sdk-for-c/pull/1338):
https://github.com/Azure/azure-sdk-for-c/blob/12de243f95a3b8755be90a2410cb45e865db43e7/eng/pipelines/templates/jobs/archetype-sdk-client.yml#L84

**Comment by antkmsft** [comment]
This PR + CI/CD update, build passes: https://github.com/Azure/azure-sdk-for-c/pull/1395

**Comment by ahsonkhan** [comment]
@BillyONeal can you cherry-pick that commit, or give @antkmsft collaborator permissions to your fork so he can add that commit to this PR directly?

**Comment by antkmsft** [comment]
https://github.com/BillyONeal/azure-sdk-for-c/pull/1

**Review by antkmsft — APPROVED** [review]

**Review by vhvb1989 — APPROVED** [review]

**Comment by ahsonkhan** [comment]
Fixes https://github.com/Azure/azure-sdk-for-c/issues/1020 on top of https://github.com/Azure/azure-sdk-for-c/pull/1338.

**Comment by ahsonkhan** [comment]
Welcome contributor number 36! :p

**Pull request merged**
