### PR TITLE
Update provisioning client parser to retain original logic for partial JSON

### PR DESCRIPTION
**Pull request by ahsonkhan**
Addressing leftover feedback from https://github.com/Azure/azure-sdk-for-c/pull/871#pullrequestreview-443507443 to retain the original logic where we don't parse through the entire JSON payload, nor validate/require that it was complete.

Also revert back the single unit test change.

### CODE REVIEW

**Comment by ahsonkhan** [comment]
CI is failing during the `cpkg install dependencies` step due to unrelated vcpkg dependency issue:
https://dev.azure.com/azure-sdk/public/_build/results?buildId=448913&view=logs&j=fca7ad6a-abde-5736-c963-c1c63f61b663&t=46d3ba00-baec-53a3-f306-09dfc5904048

```text
Building package openssl-windows[core]:x64-windows-static...
-- Downloading https://strawberry.perl.bot/download/5.30.0.1/strawberry-perl-5.30.0.1-32bit.zip...
-- Downloading https://www.openssl.org/source/openssl-1.1.1d.tar.gz...
-- Extracting source C:/vcpkg/downloads/openssl-1.1.1d.tar.gz
-- Using source at C:/vcpkg/buildtrees/openssl-windows/src/openssl-1-b1f8ae3e6c
-- Downloading http://www.nasm.us/pub/nasm/releasebuilds/2.14.02/win32/nasm-2.14.02-win32.zip...
-- Downloading http://www.nasm.us/pub/nasm/releasebuilds/2.14.02/win32/nasm-2.14.02-win32.zip... Failed. Status: 7;"Couldn't connect to server"
-- Downloading http://fossies.org/windows/misc/nasm-2.14.02-win32.zip...
-- Downloading http://fossies.org/windows/misc/nasm-2.14.02-win32.zip... Failed. Status: 22;"HTTP response code said error"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:175 (message):
      
      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:***@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_find_acquire_program.cmake:376 (vcpkg_download_distfile)
  ports/openssl-windows/portfile.cmake:27 (vcpkg_find_acquire_program)
  scripts/ports.cmake:76 (include)


Error: Building package openssl-windows:x64-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openssl-windows:x64-windows-static
  Vcpkg version: 2020.02.04-nohash

```

**Comment by ahsonkhan** [comment]
@CIPop - I would like to get this merged today, can you please review when you get some time.

**Comment by ericwol-msft** [comment]
does the sample code that uses the json parser also needs to be updated?

https://github.com/Azure/azure-sdk-for-c/blob/c9396dc3ab682a3c55c5a31c9e1070a1d28a3bd1/sdk/samples/iot/hub/src/paho_iot_hub_twin_example.c

**Comment by ahsonkhan** [comment]
> does the sample code that uses the json parser also needs to be updated?

I had already updated all the samples that use the json parser in https://github.com/Azure/azure-sdk-for-c/pull/871

If anyone has feedback on the changes, please let me know, or feel free to update it yourself:
https://github.com/Azure/azure-sdk-for-c/pull/871/files#diff-0c1c9070d4bb5b1dcbfa089f21d53afcR539

For that particular sample, I wasn't sure what exactly it was trying to accomplish (the while loop condition seemed odd to me), but I kept the logic the same, as much as possible. cc @momuno

**Comment by ahsonkhan** [comment]
Can I merge this PR? Waiting for approval.

**Comment by momuno** [comment]
I am testing atm.  Please do not merge yet.

**Comment by momuno** [comment]
Looks like the #871 commit broke the sample.  I'm not fully understanding your logic changes to that portion of it yet.  Looking at how to fix it.

**Comment by ahsonkhan** [comment]
@danewalton mentioned what could be the issue with my changes to the sample:
The following if-block needs a call to `az_json_parser_next_token`
https://github.com/Azure/azure-sdk-for-c/blob/c9396dc3ab682a3c55c5a31c9e1070a1d28a3bd1/sdk/samples/iot/hub/src/paho_iot_hub_twin_example.c#L556-L560

This should be:
```C
    else if (az_json_token_is_text_equal(&json_parser.token, reported_property_name))
    {
      // Move to the value token
      AZ_RETURN_IF_FAILED(az_json_parser_next_token(&json_parser));

      // TODO: Change back to int32_t once that is supported.
      uint32_t temp_property_value = 0;
      AZ_RETURN_IF_FAILED(az_json_token_get_uint32(&json_parser.token, &temp_property_value));

      printf(
          "Updating \"%.*s\" locally.\n",
          az_span_size(reported_property_name),
          az_span_ptr(reported_property_name));
      reported_property_value = (int32_t)temp_property_value;
      return AZ_OK;
    }
```

**Comment by danewalton** [comment]
@ahsonkhan should I submit a PR for it or is it already included in another PR?

**Comment by ahsonkhan** [comment]
> should I submit a PR for it or is it already included in another PR?

It isn't. For simplicity, I will push a commit to this PR with the fix.

**Comment by danewalton** [comment]
> It isn't. For simplicity, I will push a commit to this PR with the fix.

Much appreciated 🍾

**Comment by momuno** [comment]
Adding:

// Move to the value token
      AZ_RETURN_IF_FAILED(az_json_parser_next_token(&json_parser));

fixes it

**Comment by CIPop** [comment]
Thanks @ahsonkhan ! LGTM

**Pull request merged**
