### PR TITLE
Support building for specific platform implementations.

### PR DESCRIPTION
**Pull request by RickWinter**
The build will fail when a platform is required but not specified

This is a recreation of the portsfolder PR.  That PR had some git merge mistakes.  It was easier to replay the change on a new branch vs attempting to fix the git history of the other branch

### CODE REVIEW

**Comment by danewalton** [comment]
@RickWinter any updates here?

**Comment by ahsonkhan** [comment]
@RickWinter what's the plan for this PR?

**Comment by ahsonkhan** [comment]
@RickWinter - can we close this PR until it is ready to be re-opened?

**Comment by ahsonkhan** [comment]
Closing this PR for now. Please re-open once it is ready to be reviewed.

**Pull request closed without merging**
