### PR TITLE
Update CODEOWNERS

### PR DESCRIPTION
**Pull request by RickWinter**

### CODE REVIEW

**Review by danewalton — COMMENTED** [review]
Valerie should be restored for our files.

**Comment by RickWinter** [comment]
> Valerie should be restored for our files.

The GitHub alias was coming back as not having permissions, hence the removal.  Has she joined the proper groups?

**Comment by danewalton** [comment]
> > Valerie should be restored for our files.
> 
> 
> 
> The GitHub alias was coming back as not having permissions, hence the removal.  Has she joined the proper groups?

I believe she's putting in the request for it. You can however remove @momuno while you're in that file. She's spreading her wings and flying away from us :)

**Review by danewalton — APPROVED** [review]
Approving and we will tackle rectifying IoT codeowners in a followup

**Pull request merged**
