### PR TITLE
Clean up / Ignore unnecessary CI artifacts, Issue #1422

### PR DESCRIPTION
**Pull request by TarenLewis**
This is my first PR with an "official" repo, plz go easy. Thanks!

### CODE REVIEW

**Comment by mitchdenny** [comment]
Thanks for submitting a PR @Azure/azure-sdk-team-signalr 

Just wondering if we could get a bit more detail on the specific issue you are looking to solve with this PR. Are there files being created in ```tools``` which are making your commit experience difficult? Also with regard to deleting the ```grepResults``` file, I don't think it will have any impact since the file removal is performed after any artifacts are uploaded, and since the VM running the build is destroyed after each run its likely an unnecessary change.

**Comment by TarenLewis** [comment]
> Just wondering if we could get a bit more detail on the specific issue you are looking to solve with this PR. Are there files being created in `tools` which are making your commit experience difficult? Also with regard to deleting the `grepResults` file, I don't think it will have any impact since the file removal is performed after any artifacts are uploaded, and since the VM running the build is destroyed after each run its likely an unnecessary change.

Hi Mitch, 
This PR was in regards to the issue found here: https://github.com/Azure/azure-sdk-for-c/issues/1422
It was submitted in an attempt to satisfy the requirements located within that issue, but I didn't realize that the `grepResults` file will be deleted anyway. I was following the instructions but if the issue needs to be closed without any changes, I understand that too. Thank you, and thank you for the tip.

Taren

**Comment by ahsonkhan** [comment]
Fixes https://github.com/Azure/azure-sdk-for-c/issues/1422

**Review by ahsonkhan — APPROVED** [review]
Looks good to me. Thanks for the fix @TarenLewis :)

**Comment by ahsonkhan** [comment]
> Are there files being created in ```tools``` which are making your commit experience difficult?

If we generate code coverage locally, the tools folder gets created which needs to be ignored. Like other .gitignore files (such as DoxygenWarningLog.txt and `**/[Dd]oc/generated_doxygen_docs`), we don't want them accidentally pushed as part of a commit.

> Also with regard to deleting the ```grepResults``` file, I don't think it will have any impact since the file removal is performed after any artifacts are uploaded, and since the VM running the build is destroyed after each run its likely an unnecessary change.

I understand it isn't strictly necessary, but we are creating a file on disk to validate encoding, so it is good to clean up that file after we are done with it. I see no harm in doing so.

**Comment by mitchdenny** [comment]
LGTM then.

**Review by mitchdenny — APPROVED** [review]

**Comment by ahsonkhan** [comment]
> This is my first PR with an "official" repo

Congrats! Keep it up ;)

**Comment by TarenLewis** [comment]
> Congrats! Keep it up ;)
Thank you Ahsonkhan! I appreciate it. I am definitely looking for other ways to contribute and help in any way I can.

**Comment by ahsonkhan** [comment]
Nice. If you are interested in C and C++, here are some `help wanted` issues:

https://github.com/Azure/azure-sdk-for-cpp/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22
 - For example: https://github.com/Azure/azure-sdk-for-cpp/issues/898
https://github.com/Azure/azure-sdk-for-c/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22
 - For example: https://github.com/Azure/azure-sdk-for-c/issues/1263

Let me know if you are interested in other programming languages instead. You can look at `good first issue` labels.

**Comment by TarenLewis** [comment]
Awesome, I will start working on issue https://github.com/Azure/azure-sdk-for-cpp/issues/898 . I am interested in primarily C,C#, C++, and outside C languages possibly Python. 

Thanks for the resources!

**Comment by ahsonkhan** [comment]
@TarenLewis - shall I put you down for https://github.com/Azure/azure-sdk-for-cpp/issues/898 and remove the `help wanted` label? It isn't super urgent, but we'd like to get that fixed before end-of-year.

**Comment by TarenLewis** [comment]
@ahsonkhan I was planning on writing a python script to handle it, but I won't likely be able to start working on it for a couple weeks. I'd like to leave it open just in case someone else gets to it before me, but plan on working on it once I start my break. (I'm in finals week at university right now)

Thanks!

**Comment by ahsonkhan** [comment]
Sounds great. Good luck.

**Comment by TarenLewis** [comment]
Gotcha, thanks for the suggestion. Probably a much better solution.

**Pull request merged**
