### PR TITLE
Make repository a Zephyr module

### PR DESCRIPTION
**Pull request by simensrostad**
Add module.yml that enables Zephyr RTOS based projects to include
the repository as module.

For more information, see:
https://docs.zephyrproject.org/latest/develop/modules.html

### CODE REVIEW

**Comment by simensrostad** [comment]
@ahsonkhan @RickWinter Would it be possible to get this PR in before the 1.4.0 release?

**Comment by carlescufi** [comment]
Here's a similar PR on a Google repository:
- https://github.com/google/liblc3/pull/7

More about Zephyr modules here:
https://docs.zephyrproject.org/latest/develop/modules.html

**Review by carlescufi — APPROVED** [review]

**Review by maxd-nordic — APPROVED** [review]

**Review by gregersrygg — APPROVED** [review]

**Comment by simensrostad** [comment]
bump

**Comment by jhn-nordic** [comment]
@RickWinter 
@danewalton @vaavva @ahsonkhan (tagging some people that contributes to the Azure SDK)

This would be a nice addition to your SDK for customers that use Zephyr.

**Comment by danewalton** [comment]
Hey all thank you for the PR. Sorry we are taking a bit of time on this. We love enabling as many scenarios as possible, but we want to make sure we set expectations of support correctly. We are actively discussing this on the team. Thanks for the patience.

**Comment by simensrostad** [comment]
> Hey all thank you for the PR. Sorry we are taking a bit of time on this. We love enabling as many scenarios as possible, but we want to make sure we set expectations of support correctly. We are actively discussing this on the team. Thanks for the patience.

Any updates?

**Comment by simensrostad** [comment]
> > Hey all thank you for the PR. Sorry we are taking a bit of time on this. We love enabling as many scenarios as possible, but we want to make sure we set expectations of support correctly. We are actively discussing this on the team. Thanks for the patience.
> 
> 
> 
> Any updates?

Bump

**Comment by simensrostad** [comment]
Bump

**Pull request closed without merging**
