### PR TITLE
Add Unified Pipelines for IoT

### PR DESCRIPTION
**Pull request by danieljurek**
This adds ci.yml for the IoT service and produces doc artifacts for publishing. 

I've also had to add version.txt files in here temporarily to get the docs generating properly. They will be removed in favor of `az_version.h` in a separate PR (issue https://github.com/Azure/azure-sdk-for-c/issues/606 is tracking that effort)

### CODE REVIEW

**Comment by danieljurek** [comment]
@ericwol-msft -- This PR is now updated to build doc artifacts from the root of the `sdk/iot` service directory instead of broken out by directories (e.g. `sdk/iot/core`, etc.).  An example of the documentation generated by doxygen is vailable under the `docs` folder here: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=370097&view=artifacts&type=publishedArtifacts


What name should we use? Right now I'm calling it `az_iot` in the title: 
image

**Comment by ericwol-msft** [comment]
> @ericwol-msft -- This PR is now updated to build doc artifacts from the root of the `sdk/iot` service directory instead of broken out by directories (e.g. `sdk/iot/core`, etc.). An example of the documentation generated by doxygen is vailable under the `docs` folder here: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=370097&view=artifacts&type=publishedArtifacts
> 
> What name should we use? Right now I'm calling it `az_iot` in the title:
> image

I'm fine with the version, as long as it's the same format across the other SDK (C#/Node?Java/etc)

**Comment by danieljurek** [comment]
Check is currently sticking on these Unified Pipelines checks because I rejected the publish steps (normal for something you're not going to release). I'll be merging anyway. I was testing eng sys changes. Contributors making changes to the libraries themselves and not testing unified pipeline changes will not have to deal with this.

**Pull request merged**
