### PR TITLE
Merging main into feature/v2

### PR DESCRIPTION
**Pull request by RLeclair**

### CODE REVIEW

**Review by vaavva — APPROVED** [review]

**Review by ewertons — APPROVED** [review]
Please make sure you rebase your changes so they show up clean on top of the updates from main branch.

**Review by ronniegeraghty — APPROVED** [review]

**Review by CIPop — APPROVED** [review]
Merging from main only (no changes).

**Comment by RLeclair** [comment]
Hi @RickWinter we need to enable the option to do a merge commit for this PR, the option is disabled for this repository. Would you be able to enable it? We will need to merge from main as we make progress on the v2 branch.

**Review by RickWinter — APPROVED** [review]

**Comment by RickWinter** [comment]
@danieljurek, @weshaggard Can you confirm using a merge is the best approach.  If so can you facilitate the action for this PR

**Comment by LarryOsterman** [comment]
I believe you need to do your merge manually using the command line.

Instructions for this are here: https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/16/FAQ?anchor=i-have-a-special-case-where-i-do-not-want-to-squash-and-merge-a-pr.--what-should-i-do%3F

**Comment by danieljurek** [comment]
@RLeclair -- Follow the instructions [here](https://dev.azure.com/azure-sdk/internal/_wiki/wikis/internal.wiki/16/FAQ?anchor=i-have-a-special-case-where-i-do-not-want-to-squash-and-merge-a-pr.--what-should-i-do%3F) to merge this branch. Let me know if you encounter any problems with permissions.

**Comment by RLeclair** [comment]
Created new PR following these instructions referred to above. 

See: https://github.com/Azure/azure-sdk-for-c/pull/2555

**Pull request closed without merging**
