### PR TITLE
Fix issue in az_span_slice so that the length is set correctly and clamped at 0.

### PR DESCRIPTION
**Pull request by ahsonkhan**
~**TODO (in this PR):**~
 - [x] Add basic unit tests
 - [x] Add comments

**There were two issues here:**
1) If the caller passed in -1 for  the `end_index`, instead of setting the returned span's length to be `original length - start_index`, we were setting it to `original capacity - start_index`.
2) If the caller sliced the span past it's length, while passing -1 for the `end_index`, we would still have the length be set to some positive number, rather than clamping it to 0.

```text
az_span span = initialize from a buffer of capacity 20 with 4 bytes filled = {a, b, c, d, 0, 0, 0,...}
span.length = 4
span.capacity = 20

az_span result = slice(span, 1, -1); = {b, c, d, 0, 0, ...0}
result.length = 19 // This is wrong, should be 3.
result.capacity = 19

result = slice(span, 5, -1); = {0, 0, ..., 0}
result.length = 15 // This is wrong, the length should be 0.
result.capacity = 15
```

### CODE REVIEW

**Comment by vhvb1989** [comment]
I remembered this behavior was decided to be like it is right now based on how slice() works on golang.  @JeffreyRichter , do you remember we made the experiments in golang and slice don't care about the length of the source and just do capacity - index?
I will try to re-do the test and share here

**Comment by vhvb1989** [comment]
see golang behaviour.  @JeffreyRichter 
```go
package main

import "fmt"

func main() {
	s := []int{2, 3, 5, 7, 11, 13}  // this would be az_span to a buffer (cap=6, len=6)
	printSlice(s)

	// Slice the slice to give it zero length.
	s = s[:0]      // az_span_slice(span, 0, 0); -> len will be 0, cap wil be 6
	printSlice(s)

	// Extend its length.
	s = s[:4]     // az_span_slice(span, 0, 4) -> len 4, cap = 6
	printSlice(s)

	// Drop its first two values.
	s = s[2:]           // az_span_slice(span, 2, -1) -> len will be 2 (based on previos len of 4) , cap is 4 ( 6 - 2)
	printSlice(s)
}

func printSlice(s []int) {
	fmt.Printf("len=%d cap=%d %v\n", len(s), cap(s), s)
}
```

**Comment by JeffreyRichter** [comment]
Let's not focus on this now as we're likely getting rid of length or capacity and this will change how slice works entirely. @ahsonkhan, just leave this alone for now.

**Comment by ahsonkhan** [comment]
I believe we are currently inconsistent with golang. This PR is trying to fix that.

> // Drop its first two values.
	s = s[2:]           // az_span_slice(span, 2, -1) -> len will be 2 (based on previos len of 4) , cap is 4 ( 6 - 2)

@vhvb1989 - this is where the issue manifests where we are not setting the right length.

Here's an example of what you wrote in golang, written in C. Hopefully, that clarifies it.

```C
static void az_span_slice_tests()
{
  uint8_t buffer[] = { 2, 3, 5, 7, 11, 13 };
  az_span span = AZ_SPAN_LITERAL_FROM_INITIALIZED_BUFFER(buffer);

  assert_int_equal(az_span_length(span), 6);
  assert_int_equal(az_span_capacity(span), 6);

  span = az_span_slice(span, 0, 0);

  assert_int_equal(az_span_length(span), 0);
  assert_int_equal(az_span_capacity(span), 6);

  span = az_span_slice(span, 0, 4);

  assert_int_equal(az_span_length(span), 4);
  assert_int_equal(az_span_capacity(span), 6);

  span = az_span_slice(span, 2, -1);

  assert_int_equal(az_span_length(span), 2); // This fails, length is incorrectly set to 4.
  assert_int_equal(az_span_capacity(span), 4);
}
```

```go
package main

import "fmt"

func main() {
        s:= make([]int, 4, 20)
        printSlice(s) // az_span_slice(s, 4, 20) -> len 4, cap = 20

	printSlice(s[1:]) // az_span_slice(s, 1, -1) -> len 3, cap = 19, the bug is we are setting the len to 19

	printSlice(s[5:]) // az_span_slice(s, 5, -1) -> golang fails here, we could do that too, but this PR just sets the length to 0.
}

func printSlice(s []int) {
	fmt.Printf("len=%d cap=%d %v\n", len(s), cap(s), s)
}
```

Output:
```text
len=4 cap=20 [0 0 0 0]
len=3 cap=19 [0 0 0]
panic: runtime error: slice bounds out of range [5:4]

goroutine 1 [running]:
main.main()
	/tmp/sandbox250534101/prog.go:11 +0xa0

Program exited: status 2.
```

**Pull request merged**
