### PR TITLE
Fix vspkg on MacOS

### PR DESCRIPTION
**Pull request by danieljurek**
Install missing headers so vcpkg builds properly.

### CODE REVIEW

**Comment by bsiegel** [comment]
I'm not clear what the problem was or why it suddenly stopped working, but theoretically this step shouldn't be necessary.

What we definitely should do is to specify the exact Xcode version and deployment target when building, so that when new Xcode versions are dropped on the agents we don't suddenly stop working. In the past I have stuck with Xcode 9.4.1 because Xcode 10 changed a lot of the native compile toolchain, it deprecated libgcc and libstdc++ in favor of libc++, and moved the minumum deployment target from OS X 10.6 to 10.9. The first part shouldn't apply here since we're just writing C99, but the deployment target changes might be relevant.

**Comment by bsiegel** [comment]
We can set the version of Xcode and the associated toolchain with:

```yaml
- script: sudo xcode-select --switch /Applications/Xcode_9.4.1.app
  displayName: 'Select Xcode 9.4.1'
```

Available Xcode versions are documented here: https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/macos/macos-10.14-Readme.md#xcode

**Comment by danieljurek** [comment]
Thanks @bsiegel! This is a much better approach.

**Pull request merged**
